//Mine
export const MINE_GET_USER_INFO = 'MINE_GET_USER_INFO';
export const MINE_CHANGE_NAME = 'MINE_CHANGE_NAME';
export const WITHDRAW_GET_INFO = 'WITHDRAW_GET_INFO';
export const WITHDRAW_CONFIRM = 'WITHDRAW_CONFIRM';
export const INSTITUTION_INFO = "INSTITUTION_INFO";
export const ADDRESS_INFO = "ADDRESS_INFO";
export const CHOOSEDADD_SAVE = "CHOOSEDADD_SAVE";
export const REFRESH_WITHDRAW = "REFRESH_WITHDRAW";
export const CHOOSE_COUPON = "CHOOSE_COUPON";
export const REFRESH_ADDRES = "REFRESH_ADDRES";
export const CLEAR_USERINFO = "CLEAR_USERINFO";
export const BEST_SHARE_SELECT = "BEST_SHARE_SELECT"; //筛选
